name: nix-check

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-check:
    runs-on: ubuntu-latest
    steps:
    # For now we don't need this extra space.
    # Disabling this save ~2m for each run.
    # - name: Free Disk Space (Ubuntu)
    #   uses: jlumbroso/free-disk-space@v1.3.1
    - name: Checkout
      uses: actions/checkout@v5
    - name: Install nix
      uses: cachix/install-nix-action@v31
      with:
        install_options: --no-daemon
        nix_path: nixpkgs=channel:nixos-26.05
        extra_nix_config: |
          cores = 1
          max-jobs = 1
          extra-substituters = https://cache.nixos-cuda.org
          extra-trusted-public-keys = cache.nixos-cuda.org:74DUi4Ye579gUqzH4ziL9IyiJBlDpMRn9MBN8oNan9M=
    - name: Enable cachix
      uses: cachix/cachix-action@v17
      with:
        name: duyngb
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
        pushFilter: "(-source$|-vendor$|-vendor-staging$|-go-modules$)"
    - name: Run nix check
      run:
        nix run 'nixpkgs#nix-fast-build' --
          --no-download
          --skip-cached
          --no-nom
          --max-jobs 1
